/**
 * Copy to clipboard utility
 */

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    // Try modern clipboard API first
    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
    
    // Fallback to older method
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    textArea.style.top = '-999999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    
    try {
      const successful = document.execCommand('copy');
      document.body.removeChild(textArea);
      return successful;
    } catch (err) {
      document.body.removeChild(textArea);
      return false;
    }
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}

/**
 * Format message for sharing
 */
export function formatMessageForSharing(
  message: string,
  results?: any[],
  relatedTopics?: any[]
): string {
  let text = `Luminate AI Response:\n\n${message}\n`;
  
  if (results && results.length > 0) {
    text += '\n\nRelevant Course Materials:\n';
    results.forEach((result, index) => {
      text += `${index + 1}. ${result.title}`;
      if (result.url) {
        text += ` - ${result.url}`;
      }
      text += '\n';
    });
  }
  
  if (relatedTopics && relatedTopics.length > 0) {
    text += '\n\nRelated Topics to Explore:\n';
    relatedTopics.forEach((topic, index) => {
      text += `${index + 1}. ${topic.title}\n`;
      if (topic.why_explore) {
        text += `   ${topic.why_explore}\n`;
      }
    });
  }
  
  text += '\n\n---\nGenerated by Luminate AI - COMP237 Course Assistant';
  
  return text;
}
