-- feedback_schema.sql

-- 1) Full chat messages
CREATE TABLE IF NOT EXISTS chat_logs (
    conversation_id TEXT NOT NULL,
    turn_index      INT  NOT NULL,
    role            TEXT NOT NULL,   -- 'student' or 'assistant'
    agent           TEXT,            -- 'PlannerAgent' | 'TutorAgent' | 'MathAgent' | NULL
    content         TEXT NOT NULL,
    created_at      TIMESTAMP DEFAULT NOW()
);

-- 2) Per-conversation rating from the student
CREATE TABLE IF NOT EXISTS conversation_ratings (
    conversation_id TEXT PRIMARY KEY,
    rating          INT NOT NULL,    -- 1–5 stars
    created_at      TIMESTAMP DEFAULT NOW()
);

-- 3) Insights generated by FeedbackAgent
CREATE TABLE IF NOT EXISTS analytics_insights (
    id                     SERIAL PRIMARY KEY,
    conversation_id        TEXT,
    topic                  TEXT,
    primary_agent          TEXT,
    severity               TEXT,
    requires_human_review  BOOLEAN DEFAULT TRUE,
    summary                TEXT,
    raw_json               JSONB,
    generated_at           TIMESTAMP DEFAULT NOW()
);
